language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
      # support CC=gcc ARCH=x86:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y gcc-multilib; fi
      # support CC=clang ARCH=x86:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y gcc-4.9-multilib; fi

env:
  - ARCH=x64
  - ARCH=x86

script:
    - ./test/run.sh
  
# only trigger build for pushes on master branch
branches:
  only:
    - master
